name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Habilita execução manual pelo botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: ReactiveCircus/android-sdk-setup-action@v2
        with:
          sdk-version: '33'  # Ou outra versão que você esteja utilizando
          ndk-version: '21.4.7075529'  # NDK versão necessária

      - name: Install dependencies
        run: |
          yes | sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-33"  # Ajuste conforme a sua versão
          ./gradlew --no-daemon clean

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon  # Usar o wrapper do gradle para construir

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
