name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Habilita execução manual pelo botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        run: |
          # Instala o Android SDK
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
          unzip commandlinetools-linux-8092744_latest.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-33" "ndk;21.4.7075529"

      - name: Install dependencies
        run: |
          ./gradlew dependencies --no-daemon  # Baixa as dependências do Gradle

      - name: Build APK
        run: |
          ./gradlew assembleDebug --no-daemon  # Usar o wrapper do gradle para construir

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
